"""Canonical event names used by StructuredLogger.event() and the mission FSM engine.

Centralising these prevents typos and lets tools (status, log-events, e2e-report)
discover the full taxonomy.
"""

from __future__ import annotations

# Mission phase transitions and milestones (emitted by the mission FSM engine).
PHASE_CHANGE = "PHASE_CHANGE"
WAYPOINT_REACHED = "WAYPOINT_REACHED"
MISSION_DONE = "MISSION_DONE"
MARKER_ACQUIRED = "MARKER_ACQUIRED"
MARKER_LOST = "MARKER_LOST"
MARKER_HOVER_START = "MARKER_HOVER_START"
TARGET_POSE_STALE = "TARGET_POSE_STALE"
TARGET_YAW_MALFORMED = "TARGET_YAW_MALFORMED"

# Arming / mode handshake (emitted by offboard_controller).
ARM_COMMAND_SENT = "ARM_COMMAND_SENT"
ARM_ACK_OK = "ARM_ACK_OK"
ARM_ACK_DENIED = "ARM_ACK_DENIED"
OFFBOARD_MODE_COMMAND = "OFFBOARD_MODE_COMMAND"
TAKEOFF_COMMAND_SENT = "TAKEOFF_COMMAND_SENT"
AUTO_ARM_DISABLED_ON_DISARM = "AUTO_ARM_DISABLED_ON_DISARM"
AUTO_ARM_LATCH_CLEARED_BY_PARAM = "AUTO_ARM_LATCH_CLEARED_BY_PARAM"
FAILSAFE_MODE_COMMANDS_LATCHED = "FAILSAFE_MODE_COMMANDS_LATCHED"
FAILSAFE_CLEARED_LIVE = "FAILSAFE_CLEARED_LIVE"
FAILSAFE_LATCH_CLEAR_REJECTED = "FAILSAFE_LATCH_CLEAR_REJECTED"
